model_type: "smolvla"
model_path: "DorianAtSchool/smolvla-finetune-franka-pickplace-combined"
precision: null

num_action_chunks: 10
action_dim: 7
num_steps: 10
add_value_head: True
use_proprio: True

is_lora: True
lora_rank: 32

smolvla:
  train_expert_only: False
  noise_level: 0.0
  noise_method: "flow_sde"
  action_chunk: ${actor.model.num_action_chunks}
  action_env_dim: ${actor.model.action_dim}
  num_steps: ${actor.model.num_steps}
  add_value_head: ${actor.model.add_value_head}
  value_after_vlm: True
  value_vlm_mode: "mean_token"
  joint_logprob: False
  num_images_in_input: 3
